insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Ultračirá samolepka, monomér'	),	unnest(string_to_array(	'137'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Samolepka monomer bílá s GudyDot lepidlem'	),	unnest(string_to_array(	'137'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Samolepka Polymerická s kanálkovým lepidlem'	),	unnest(string_to_array(	'137, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC laminace se strukturou CANVAS'	),	unnest(string_to_array(	'130'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Antigraffiti Laminace'	),	unnest(string_to_array(	'130'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Tabulová Laminace'	),	unnest(string_to_array(	'130'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Samolepka Podlahová'	),	unnest(string_to_array(	'130'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Podlahová Laminace 6 měsíců'	),	unnest(string_to_array(	'130'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Wallwrapová Folie 200'	),	unnest(string_to_array(	'137'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Wallwrapová Folie 100'	),	unnest(string_to_array(	'137'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Reflexní Folie rovné plochy'	),	unnest(string_to_array(	'120'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PVC Reflexní Folie mírné prolisy'	),	unnest(string_to_array(	'120'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'adhezivní folie bílá nebo čirá'	),	unnest(string_to_array(	'127'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Yupo Tako - XAD1069'	),	unnest(string_to_array(	'127'	,','))::float,	'20000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Samolepící textil'	),	unnest(string_to_array(	'127, 137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Mesh'	),	unnest(string_to_array(	'160'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Banner se strukturou canvas'	),	unnest(string_to_array(	'160'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Backlite - pouze UV + 130,- za inkoust navíc a pomalý tisk'	),	unnest(string_to_array(	'106, 137, 152'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'PP Octopus'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'DIGIFORT WALL P 13003 DUST 1300/50'	),	unnest(string_to_array(	'130'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Coala Walldesign Glass Fiber Embossed Prepasted'	),	unnest(string_to_array(	'100, 137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'BERGER 4637-66 BE SALSA DEYLUX 150g'	),	unnest(string_to_array(	'160'	,','))::float,	'80000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Gelová páska 25mm'	),	unnest(string_to_array(	'25'	,','))::float,	'33000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Magnetická folie tl.0,9mm'	),	unnest(string_to_array(	'62'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	286	,	idefix_mat(	'Magnetická folie tl.1,5mm'	),	unnest(string_to_array(	'62'	,','))::float,	'10000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Samolepka Monomerická'	),	unnest(string_to_array(	'106, 137, 160'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Laminace Monomerická'	),	unnest(string_to_array(	'106, 137, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Laminace Monomerická na UV tisky'	),	unnest(string_to_array(	'137, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Samolepka Polymerická'	),	unnest(string_to_array(	'106, 137, 160'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Laminace Polymerická'	),	unnest(string_to_array(	'106, 137, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Samolepka Litá'	),	unnest(string_to_array(	'106, 137, 155'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Laminace Litá'	),	unnest(string_to_array(	'106, 137, 155'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Ultračirá samolepka, litá'	),	unnest(string_to_array(	'137'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Polymerická Translucentní'	),	unnest(string_to_array(	'106, 137, 160'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Oneway folie bez certifikace'	),	unnest(string_to_array(	'137, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Oneway folie s certifikací'	),	unnest(string_to_array(	'137, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Podlahová Laminace 3 měsíce'	),	unnest(string_to_array(	'130, 152'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PVC Wallwrapová Folie 300'	),	unnest(string_to_array(	'137'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Fotopapír Satén 205gsm'	),	unnest(string_to_array(	'91, 106, 137, 152'	,','))::float,	'61000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Fotopapír Lesklý 260gsm'	),	unnest(string_to_array(	'91, 106, 137, 152'	,','))::float,	'61000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'CLV 150gsm'	),	unnest(string_to_array(	'137'	,','))::float,	'100000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'CLV 200gsm'	),	unnest(string_to_array(	'137'	,','))::float,	'100000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Blueback 115gsm'	),	unnest(string_to_array(	'137'	,','))::float,	'100000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Ofsetový papír 90gsm'	),	unnest(string_to_array(	'106'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Levný banner 550gsm'	),	unnest(string_to_array(	'110, 155'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Blockout banner 510gsm'	),	unnest(string_to_array(	'110, 155'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Backlite + 130,- za inkoust navíc a pomalý tisk'	),	unnest(string_to_array(	'106, 137, 152'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'PP Rollup - nolite'	),	unnest(string_to_array(	'106, 127, 155'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign NV UV/LX - 150g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign NW Smooth Matt - 350g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign NV Canvas - 350g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign NV Brush - 350g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign P Sand - 300g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign P Smooth Matt - 300g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign P Fine Sand - 300g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign P Canvas - 300g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'WallDesign P Stucco - 300g'	),	unnest(string_to_array(	'137'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Poly-tex SB matt 260g'	),	unnest(string_to_array(	'106,7, 137, 152'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Canvas 370gsm'	),	unnest(string_to_array(	'106, 137, 152'	,','))::float,	'23000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Polyester Backlit 170 gsm'	),	unnest(string_to_array(	'160,2'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Přenoska papírová'	),	unnest(string_to_array(	'122'	,','))::float,	'100000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Přenoska PVC pomeranč'	),	unnest(string_to_array(	'122'	,','))::float,	'100000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Přenoska PVC'	),	unnest(string_to_array(	'100'	,','))::float,	'100000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Oboustranka celoplošná - Symbio'	),	unnest(string_to_array(	'104, 130, 154'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Oboustranka GUDYDOT'	),	unnest(string_to_array(	'104, 130, 140,'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Akrylová oboustranka 19mm'	),	unnest(string_to_array(	'19'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Akrylová oboustranka 9mm'	),	unnest(string_to_array(	'9'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Pěnovka 19mm'	),	unnest(string_to_array(	'19'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Pěnovka 12mm'	),	unnest(string_to_array(	'12'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Oboustranka na papír 19mm'	),	unnest(string_to_array(	'19'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Oboustranka na papír 9mm'	),	unnest(string_to_array(	'9'	,','))::float,	'50000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Suchý zip háčky, smyčky'	),	unnest(string_to_array(	'20,25,50'	,','))::float,	'8000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Magnetická folie tl.0,5mm'	),	unnest(string_to_array(	'62, 100'	,','))::float,	'25000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	285	,	idefix_mat(	'Magnetická folie tl.0,7mm'	),	unnest(string_to_array(	'62'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Potisknutelný textil samolepící - Gekko-Tex'	),	unnest(string_to_array(	'127, 137, 152'	,','))::float,	'30000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery 500 – monomer'	),	unnest(string_to_array(	'61, 123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery 700 – polymer'	),	unnest(string_to_array(	'61, 123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery 800 – litá'	),	unnest(string_to_array(	'123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery SWF – litá wrapping'	),	unnest(string_to_array(	'152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery NV 500 – reflexní'	),	unnest(string_to_array(	'123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery zrcadlová zlatá/stříbrná'	),	unnest(string_to_array(	'123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Aslan – dry apply, písková'	),	unnest(string_to_array(	'126, 152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Avery Wrap Gloss Metalic Silver'	),	unnest(string_to_array(	'152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Mactac 8300 – monomer'	),	unnest(string_to_array(	'61, 123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Mactac 9800 – polymer'	),	unnest(string_to_array(	'61, 123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Tuning film 700BF'	),	unnest(string_to_array(	'152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Mactac 8900 – na ploché stěny'	),	unnest(string_to_array(	'123'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Hexis 20000 – litá'	),	unnest(string_to_array(	'137, 152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'3M SC 50 - polymer'	),	unnest(string_to_array(	'122'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'3M SC 80 - litá'	),	unnest(string_to_array(	'122'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'3M 1080 - Wrapping barvy'	),	unnest(string_to_array(	'152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'3M 1080 - Wrapping metalické'	),	unnest(string_to_array(	'152'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Tabulovka – černá'	),	unnest(string_to_array(	'137'	,','))::float,	'1000'	;
insert into list_mat_rozmer(idefix_dostupnost,idefix_mat,sirka_mm,vyska_mm)		select 	284	,	idefix_mat(	'Tabulovka – čirá'	),	unnest(string_to_array(	'137'	,','))::float,	'1000'	;
