insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Foam X (Kapa - Papírová) 10'	,	'10'	,	'Pěnová deska se žlutým jádrem, oboustranně potisknutelná, papírový povrch, poze na objednání, dodací termín až 1 měsíc!!!'	,	'225'	,	'10 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Foam X (Kapa - Papírová) 5'	,	'5'	,	'Pěnová deska se žlutým jádrem, oboustranně potisknutelná, papírový povrch, poze na objednání, dodací termín až 1 měsíc!!!'	,	'140'	,	'5 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Foam X (Kapa - Papírová) 3'	,	'3'	,	'Pěnová deska se žlutým jádrem, oboustranně potisknutelná, papírový povrch, poze na objednání, dodací termín až 1 měsíc!!!'	,	'120'	,	'3 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kapa Line - Papírová pěnová 3'	,	'3'	,	'Pěnová deska se žlutým jádrem, oboustranně potisknutelná, papírový povrch, poze na objednání, dodací termín až 1 měsíc!!!'	,	'160'	,	'3 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kapa Line - Papírová pěnová 5'	,	'5'	,	'Pěnová deska se žlutým jádrem, oboustranně potisknutelná, papírový povrch, poze na objednání, dodací termín až 1 měsíc!!!'	,	'230'	,	'5 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kapa Line - Papírová pěnová 10'	,	'10'	,	'Pěnová deska se žlutým jádrem, oboustranně potisknutelná, papírový povrch, poze na objednání, dodací termín až 1 měsíc!!!'	,	'260'	,	'10 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kapa Plast - Plastová pěnová  10'	,	'10'	,	'Pěnová deska s šedým jádrem, oboustranně potisknutelná, plastový povrch, pevnější než papírová'	,	'395'	,	'10 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kapa Plast - Plastová pěnová  5'	,	'5'	,	'Pěnová deska s šedým jádrem, oboustranně potisknutelná, plastový povrch, pevnější než papírová'	,	'300'	,	'5 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kapa Plast - Plastová pěnová  3'	,	'3'	,	'Pěnová deska s šedým jádrem, oboustranně potisknutelná, plastový povrch, pevnější než papírová'	,	'260'	,	'3 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Stadur - Plastová s pěnovým jádrem  10'	,	'10'	,	'Pevná deska s povrchem z pěněného PVC a polyuretanovým jádrem, velmi pevná, plastový povrch určený'	,	'365'	,	'10 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Stadur - Plastová s pěnovým jádrem  5'	,	'5'	,	'k oboustrannému potisku, NELZE řezat malé poloměry!'	,	'330'	,	'5 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Smart X (varianta Staduru) 0'	,	'0'	,	'Totéž co Stadur, jen jiný obchodní název, provedení 5mm, 10mm.'	,	'0'	,	'0 mm'	,idefix_vyrobce(	'Kapa'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex Digital - Pěněné PVC 3'	,	'3'	,	'Pěněná PVC deska s digitálním coatingem pro UV potisk, perfektní bělost, preferovaný materiál pro potisk'	,	'160'	,	'3 mm'	,idefix_vyrobce(	'Simona'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex Digital - Pěněné PVC 5'	,	'5'	,	'Exkluzivní materiál - nikdo jiný v ČR jej nenabízí.'	,	'260'	,	'5 mm'	,idefix_vyrobce(	'Simona'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 10'	,	'10'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'390'	,	'10 mm'	,idefix_vyrobce(	'Falcon'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 8'	,	'8'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'350'	,	'8 mm'	,idefix_vyrobce(	'Falcon'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 6'	,	'6'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'300'	,	'6 mm'	,idefix_vyrobce(	'Ongro'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 5'	,	'5'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'210'	,	'5 mm'	,idefix_vyrobce(	'Simona'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 4'	,	'4'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'180'	,	'4 mm'	,idefix_vyrobce(	'Simona'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 3'	,	'3'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'130'	,	'3 mm'	,idefix_vyrobce(	'Simona'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 2'	,	'2'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'105'	,	'2 mm'	,idefix_vyrobce(	'Simona'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC 1'	,	'1'	,	'Pěněná PVC deska s krytou stranou pro UV potisk, v tloušťce 3 nebo 5 mm lze i oboustranně krytá ale cena je vyšší o 30kč na metr čtvereční'	,	'71'	,	'1 mm'	,idefix_vyrobce(	'Falcon'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex originál 0'	,	'0'	,	'Cena i rozměry jako Simona, kvalita výrazně vyšší.'	,	'0'	,	'0 mm'	,idefix_vyrobce(	'Forex'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC barevné 5'	,	'5'	,	'Deska z pěněného PVC, pevná, oboustranný potisk, barevná podle vzorníku'	,	'270'	,	'5 mm'	,idefix_vyrobce(	'Palfoam'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Forex - Pěněné PVC barevné 3'	,	'3'	,	'Standartně skladem černé desky, ostatní na objednání'	,	'220'	,	'3 mm'	,idefix_vyrobce(	'Vikupor'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'PVC - Iroplast 0.5'	,	'0.5'	,	'Tenký plast, nepotiskáváme pouze kašírujeme'	,	'50'	,	'0.5 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Pentaprint 0.3'	,	'0.3'	,	'Tvrdé PVC k přímému potisku i ke kašíru (jsou i tloušťky 0.15 - 0,7mm), čirý, bílý'	,	'58'	,	'0.3 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'PET-G 0.5'	,	'0.5'	,	'Polyethylen k přímému potisku i ke kašíru (jsou i tloušťky 0,3/0,7/1mm, čirý, mléčný, bílý'	,	'59'	,	'0.5 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Dibond Hliníkový kompozit 0,21mm 3'	,	'3'	,	'Bílo-bílá deska s jádrem z tvrzeného PVC, určeno do exteriéru, kašírované nebo s přímým potiskem,'	,	'410'	,	'3 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Dibond Hliníkový kompozit 0,21mm 2'	,	'2'	,	'Bílo-bílá deska s jádrem z tvrzeného PVC, určeno do exteriéru, kašírované nebo s přímým potiskem,'	,	'380'	,	'2 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'orig. 6'	,	'6'	,	'Bílo-bílá deska s jádrem z tvrzeného PVC, určeno do exteriéru, kašírované nebo s přímým potiskem,'	,	'854'	,	'6 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'anglický bílý (mat/mat)  4'	,	'4'	,	'Bílo-bílá deska s jádrem z tvrzeného PVC, určeno do exteriéru, kašírované nebo s přímým potiskem,'	,	'405'	,	'4 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kartonové vlny 4'	,	'4'	,	'Krabicový karton, hnědo-hnědý, nepotisknutelný, nekašírovatelný, pouze na balení B vlna h/h 3VVL, 1deska 39 Kč'	,	'15'	,	'4 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kartonové vlny 1'	,	'1'	,	'3vrstvá vlna, bílo-bílá, potisknutelné jednostranně na UV, kašírovatelné / E vlna b/b 3VVL'	,	'29'	,	'1 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kartonové vlny 1'	,	'1'	,	'3vrstvá vlna, hnědo hnědá, E vlna h/h 3VVL'	,	'9'	,	'1 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kartonové vlny 4'	,	'4'	,	'5vrstvá vlna, bílo-bílá, potisknutelné jednostranně na UV, kašírovatelné, pevná balení / EB vlna b/b 5VVL'	,	'34'	,	'4 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Kartonové vlny 3'	,	'3'	,	'5vrstvá vlna, bílo-bílá, potisknutelné jednostranně na UV, kašírovatelné, / EE vlna b/b 5VVL'	,	'31'	,	'3 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'GT2 Ultraboard plus 450g  0.3'	,	'0.3'	,	'bílo-bílý karton, potisknutelné jednostranně na UV, kašírovatelné'	,	'13.5'	,	'0.3 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'GD2 Ultraboard 450g 0.3'	,	'0.3'	,	'bílo-šedý karton, potisknutelné jednostranně na UV, kašírovatelné'	,	'13.5'	,	'0.3 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Carrier kraft 330g 0'	,	'0'	,	'bílo-hnědý karton, potisknutelné jednostranně na UV, kašírovatelné'	,	'15'	,	'0 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Ensocoat 350g 0'	,	'0'	,	'bílo-bílý (pohlednicový karton), potisknutelý na UV, '	,	'11'	,	'0 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'KATZ Board 2'	,	'2'	,	'Bílo-bílý, oboustranný potisk, drahý výřez do tvaru (řežeme oscilátorem)'	,	'88'	,	'2 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Eskaduo 1'	,	'1'	,	'Bílo-bílý, oboustranný potisk '	,	'30'	,	'1 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Eskamono  2'	,	'2'	,	'bílo/šedá, jednostranný potisk, kašír'	,	'45'	,	'2 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Voštinová deska Re-board basic 10'	,	'10'	,	'Pevná kartonová deska s plástvovým vnitřkem, ideální pro konstrukce s pomocí v-cutu'	,	'254'	,	'10 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Voštinová deska Re-board basic 16'	,	'16'	,	'Pevná kartonová deska s plástvovým vnitřkem, ideální pro konstrukce s pomocí v-cutu'	,	'326'	,	'16 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Voštinová deska Re-board premium s certifikátem FSC 10'	,	'10'	,	'Pevná kartonová deska s plástvovým vnitřkem, ideální pro konstrukce s pomocí v-cutu'	,	'295'	,	'10 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Dutinka - kartonplast 5'	,	'5'	,	'Pevná kartonová deska s plástvovým vnitřkem, ideální pro konstrukce s pomocí v-cutu'	,	'0'	,	'5 mm'	,idefix_vyrobce(	'Iroplast'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'DISPA - super papírová deska 3.8'	,	'3.8'	,	'5vrstvá celopapírová deska, bílo-bílá, hladká a krásně bílá a pevná, potisknutelné oboustranně na UV, kašírovatelné. Dobrá náhrada Kapa desek - nejde bigovat - pouze V-cut'	,	'100'	,	'3.8 mm'	,idefix_vyrobce(	'3A composite'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'HPS  1'	,	'1'	,	'Celoplastová desky z houževnatého polystyrenu, potisknutelná,vhodná na tepelný'	,	'102'	,	'1 mm'	,idefix_vyrobce(	'3A composite'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'HPS  2'	,	'2'	,	'ohyb, Neobsahuje PVC!!!'	,	'215'	,	'2 mm'	,idefix_vyrobce(	'3A composite'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'HPS  3'	,	'3'	,	'M/M = mat/mat, L/M = lesk/mat'	,	'300'	,	'3 mm'	,idefix_vyrobce(	'3A composite'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Pěněný polypropylen 3'	,	'3'	,	'bílý'	,	'215'	,	'3 mm'	,idefix_vyrobce(	'3A composite'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Crylon čirý 3'	,	'3'	,	'extrudovaná akrylová deska, UV tisk'	,	'420'	,	'3 mm'	,idefix_vyrobce(	'3A composite'	)	);
insert into list_mat(idefix_matskup,idefix_matsubskup,txt,sila_mm,popis,cena_nakup_m2,nazev3,idefix_vyrobce) values(274,2312,	'Crylon čirý 5'	,	'5'	,	'extrudovaná akrylová deska, UV tisk'	,	'690'	,	'5 mm'	,idefix_vyrobce(	'3A composite'	)	);


-- update  list_mat set txt=txt||' mm' where idefix_matskup  = '274';

 select txt,idefix_mat(txt), (string_to_array(txt,' '))[1]  from list_mat   where idefix_matskup  = '274';

update list_mat xx set nazev1 = aa, nazev3 = cc from (
 select idefix , ar[1] aa, ar[array_upper(ar,1)-1]||' '||ar[array_upper(ar,1)] as ccfrom (
 select idefix,idefix_mat(txt), (string_to_array(txt,' ')) as ar from list_mat   where idefix_matskup  = '274'
 ) a ) ax where xx.idefix = ax.idefix;


 update  list_mat set nazev2 =  replace(replace(txt, nazev1,''),nazev3,'')  where idefix_matskup = 274


